name: morphe
description: "Self improvment app with AI"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_ai: ^3.2.0
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  cupertino_icons: ^1.0.8
  modal_progress_hud_nsn: ^0.5.0
  toastification: ^3.0.2
  intl: ^0.20.2
  provider: ^6.1.4
  flutter_popup_card: ^0.0.6
  uuid: ^4.5.1
  table_calendar: ^3.2.0
  go_router: ^16.2.2
  dashed_circular_progress_bar: ^0.0.6
  percent_indicator: ^4.2.5
  http: ^1.4.0
  pair: ^0.1.2
  flutter_dotenv: ^6.0.0
  google_mobile_ads: ^6.0.0
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  hive_ce: ^2.13.3
  hive_ce_flutter: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Medium.ttf
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-MediumItalic.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf

  assets:
    - assets/images/
    - assets/images/tree/
    - assets/fonts/
    - .env
